import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import type { inferProcedureOutput } from "@trpc/server";
import type { AppRouter } from "@pickle-app/api";
import { useAuth, UserButton, useUser } from "@clerk/nextjs";
import Link from "next/link";

const Home: NextPage = () => {
  const { isSignedIn } = useAuth();
  const { user } = useUser();
  const clerkUserId: string = user?.id ?? "";

  if (isSignedIn) {
    const { data: userProfile } = trpc.profile.byId.useQuery(clerkUserId);
    if (userProfile != null) {
      userProfile.freshLogin;
      console.log("hey!");
    } else {
      console.log("Hi");
      // user profile doesn't exist at all.
    }
  }

  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col bg-gradient-to-b from-[#6220c0] to-black text-white">
        <div
          id="Header"
          className="flex h-1/5 w-full items-center justify-start p-32"
        >
          {isSignedIn ? <div>I'm Signed In!</div> : <div>Welcome!</div>}
        </div>
        <div
          id="Body"
          className="flex h-3/5 w-full items-center justify-center p-32"
        >
          Some Content
        </div>
        <div id="SignIn" className="flex h-1/5 w-full justify-center p-32">
          <Link href={"/sign-in"}>
            <button className="border-solid border-white">Sign In!</button>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { isSignedIn } = useAuth();
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined,
    { enabled: !!isSignedIn },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      {isSignedIn && (
        <>
          <p className="text-center text-2xl text-white">
            {secretMessage && (
              <span>
                {" "}
                {secretMessage} click the user button!
                <br />
              </span>
            )}
          </p>
          <div className="flex items-center justify-center">
            <UserButton
              appearance={{
                elements: {
                  userButtonAvatarBox: {
                    width: "3rem",
                    height: "3rem",
                  },
                },
              }}
            />
          </div>
        </>
      )}
      {!isSignedIn && (
        <p className="text-center text-2xl text-white">
          <Link href="/sign-in">Sign In</Link>
        </p>
      )}
    </div>
  );
};
